name: api_football
description: A package to consume api-football.com API.
version: 1.2.1
homepage: https://www.api-football.com
repository: https://github.com/jbdujardin/api_football
issue_tracker: https://github.com/jbdujardin/api_football/issues
documentation: https://github.com/jbdujardin/api_football

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.16.0
